#!/bin/bash
#
# This script deletes backup files older than 30 days and creates a new backup. You can use a cron job to execute it regularly.
#
# Copyright (c) 2025 D3ns0n
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

backup_directory="$HOME/vaultwarden/backups"
backup_filename_data="$backup_directory/data/$(date +%Y-%m-%d).sqlite3"
backup_filename_env="$backup_directory/env/.env_$(date +%Y-%m-%d)"

# delete backups older than 30 days
echo "Cleaning up backup files older than 30 days..."
find "$backup_directory" -mtime +30 -type f -print -delete
printf "done.\n\n"

# backup data
echo "Backup data to '$backup_filename_data'"
sqlite3 ~/vaultwarden/data/db.sqlite3 ".backup '$backup_filename_data'"
printf "done.\n\n"

# backup .env
echo "Backup .env to '$backup_filename_env'"
cp ~/vaultwarden/.env "$backup_filename_env"
printf "done.\n\n"